services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    secrets:
      - db_root_password
      - db_user_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_user_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
      
    secrets:
      - db_user_password
      - wp_admin_password
      - wp_user_password
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_user_password
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_USER_PASSWORD_FILE=/run/secrets/wp_user_password
      - WP_TITLE=${WP_TITLE}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always
    expose:
      - "9000"

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: always

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge
  

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt